version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - my_network
    ports:
      - 27017:27017

  back:
    build:
      context: ./Backend  # Ruta al directorio que contiene el Dockerfile
      dockerfile: Dockerfile  # Nombre del Dockerfile
    container_name: back
    networks:
      - my_network
    ports:
      - 80:80

  front:
    build:
      context: ./Prueba  # Ruta al directorio que contiene el Dockerfile
      dockerfile: Dockerfile  # Nombre del Dockerfile
    container_name: front
    networks:
      - my_network
    ports:
      - 3000:80

networks:
  my_network:
    driver: bridge
